services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
#      - ./create-db.sql:/docker-entrypoint-initdb.d/create_database.sql
    network_mode: host

volumes:
  db: